### PR TITLE
Deb build script and flexible dependency install script

### PR DESCRIPTION
**Pull request by Zipdox**
- Merged dependency install scripts so that they check apt-cache to check which packages the distro has and install the available one
- Created a script for building deb packages

Possible additions:
- Automatically add version to deb package instead of manually editing DEBIAN/control

### CODE REVIEW

**Comment by matthewevans** [comment]
@Zipdox Thanks for submitting the pull request. I created some build scripts to do deb/rpm builds by creating a fresh Docker container, checking out source, doing the build, and using fpm to create the appropriate deb/rpm (depending on the distro).

This works so far, with the next step using the gh-pages branch of this repo to host the apt and yum repositories. The idea was to add a github webhook on commit to trigger a lambda function that updates the repos (beta channel), along with another lambda function for deploying to stable when necessary.

At this point we just need to set up the lambda functions + EFS + webhooks. I like some of the improvements in your script utilizing apt-cache and think it might be helpful to integrate them.

Is this something you'd be interested in collaborating on or discussing further, possibly in the SonoBus Discord? As you seem familiar with the Debian deployment/distribution process I'm open to your thoughts/ideas on this proposed process. Thanks!

**Comment by Zipdox** [comment]
There's a sonobus discord?

**Comment by essej** [comment]
Hey Zipdox, can you rebase this PR against develop and push it again?

**Comment by Zipdox** [comment]
Gonna open new one

**Pull request closed without merging**
